name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging
      run: |
        echo "Current directory:"
        pwd

        echo "Files in the current directory:"
        ls -al

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 0.6.9
      run: bun install
      run: bun index.ts
      run: bun run build

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test
      working-directory: .
